import { ExternalLink, Mail, MessageCircle } from "lucide-react";
import Image from "next/image";
import Link from "next/link";
import { Container } from "@/components/ui/container";
import { business } from "@/data/business";

export function Footer() {
  return <footer className="site-footer"><Container className="footer-grid"><div><Link className="brand" href="/"><Image className="brand-avatar" src="/branding/phil-avatar.png" width={48} height={48} alt="" /><span className="brand-text">Phil Multi-Services<small>Votre artisan de proximité</small></span></Link><p className="footer-about">Réparation d’électroménager, pièces détachées, location et matériel reconditionné à Saint-Amand-les-Eaux.</p></div><div><h2 className="footer-title">Navigation</h2><nav className="footer-links" aria-label="Navigation de pied de page"><Link href="/">Accueil</Link><Link href="/services">Services</Link><Link href="/a-propos">À propos</Link><Link href="/contact">Contact</Link></nav></div><div><h2 className="footer-title">Nous trouver</h2><address className="footer-address">{business.address}<br />{business.postalCode} {business.city}<br /><a href={business.phoneHref}>{business.phone}</a><br /><a href={business.emailHref}>{business.email}</a></address><div className="footer-socials"><a href={business.emailHref}><Mail size={18} aria-hidden="true" /> E-mail</a><a href={business.whatsappHref} target="_blank" rel="noopener noreferrer"><MessageCircle size={18} aria-hidden="true" /> WhatsApp</a><a href={business.socialLinks.facebook ?? undefined} target="_blank" rel="noopener noreferrer"><ExternalLink size={18} aria-hidden="true" /> Facebook</a></div></div></Container><div className="footer-bottom"><Container>© {new Date().getFullYear()} Phil Multi-Services — Artisan local à Saint-Amand-les-Eaux.</Container></div></footer>;
}
